### PR TITLE
Add yaml config

### LINKED ISSUE #5: Custom Icon Mapping
As a user, I want to customize what icons are associated with what window names.

I think a yaml file could work pretty well for this (ex: `tmux-nerd-font-window-names.conf`)

```conf
icons:
  fish: '󰻳'
  python: 'שׂ'
```

The script would check for any customizations and use defaults as a fallback.

### PR DESCRIPTION
**Pull request by joshmedeski**
Closes #5

### CODE REVIEW

**Comment by joshmedeski** [comment]
@kenos1, can you look this over and give me feedback?

Also, what is the `shell.nix` and do you think it's a good idea to keep this in the repo?

**Comment by juni-purr** [comment]
Oh the shell.nix was to enter a temporary environment with `yq`, `bash-language-server` and `tmux`. It is no longer needed. I was using it mainly to test `yq` without installing it and to use a LSP for bash for my text editor.

**Comment by juni-purr** [comment]
Yeah, it looks good! Adding regex may also be useful but we will need to find a way to make that work. For now, I think just pushing this feature out in its form of basic yaml configuration when it's working fine should be enough.

Another suggestion I just thought of now is setting a custom window name format. Having an option to just show the icon and name in one format may be limiting to some people. This is probably easy to implement using `sed` though.

**Comment by joshmedeski** [comment]
I plan on merging and releasing this next week

**Comment by juni-purr** [comment]
We should also notify users about breaking changes. Though it is just 2 options, users might be confused on why it broke.

**Comment by joshmedeski** [comment]
I'm thinking we can deprecate the options rather than break them. I can add notes to the release notes and README.

**Comment by juni-purr** [comment]
Hey, it's been a month and this hasn't been merged yet. Should we merge now?

**Comment by oschrenk** [comment]
Was about to issue a PR that adds Java with `nf-fae-java` as an icon to the old style. Will wait until this is merged.

**Pull request merged**
